version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8586:8586"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://products_db:5432/products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - products_db
    networks:
      - backend

  products_db:
    image: postgres:15
    container_name: products_db
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432" # internal 5432 → exposed 5433 to avoid host port clashes
    networks:
      - backend

networks:
  backend:
    driver: bridge