version: '3.8'

services:
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8587:8587"
    environment:
      - MONGODB_URI=mongodb+srv://prachibansal135:1234@cluster0.8qq8xwu.mongodb.net/inventory?retryWrites=true&w=majority
    networks:
      - micro-net

networks:
  micro-net:
    external: true